<a href="https://colab.research.google.com/github/Tim-R413/Deep-Learning-Handbook/blob/Testing-Layout/Section%202%20-%20Applied%20Math%20and%20ML/Module%202.4%20-%20Machine%20Learning%20Basics/Module_2_4_Machine_Learning_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=10
print(a)

10


Google Colaboratory adalah  **Jupyter Notebook** gratis yang tidak memerlukan setting dan instalasi serta sepenuhnya berjalan **di cloud environment milik Google**.

Dengan Google Colaboratory kita dapat menulis dan mengeksekusi kode Python dengan mudah melalui browser (bahkan bisa dari **browser mobile**).

Kita juga dapat sharing code beserta hasilnya dengan sangat mudah melalui **Google Drive**. 


### Intro to Python

Coba beberapa script Python di bawah. 

Disetiap cell ada tombol **play** di kiri yang gunanya untuk eksekusi kode.

In [ ]:
#Coba code dibawah 
print("Hello")

Hello


In [ ]:
a=10 #Deklarasi Variabel sekaligus assignment
if a>5: #Struktur if-nya menggunakan indentasi sebagai nested 
  print("a lebih dari 5")
else:
  print("a kurang atau sama dengan 5")



a lebih dari 5


In [ ]:
a=[1,2,3,4] #List di Python (Python Collection) 
for i in a: #struktur for di python
  print (i)

1
2
3
4


In [ ]:
def Cetak_n_angka(n): #deklarasi function
  for i in range(n):
    print (i,end = ' ') #Mencetak tanpa newline
    
Cetak_n_angka(8)

0 1 2 3 4 5 6 7 

Variabel di Jupyter Notebook berlaku global bukan lokal per cell.

Variabel lokal per function tetap dapat dibuat. 

Auto complete (ctrl+spasi) tetap bisa dipakai tetapi **tidak sebaik** di **VS Code** atau **Pycharm**

Belajar Python lebih jauh: **https://www.w3schools.com/python/**



### Simple Machine Learning

#### Masalah Klasifikasi Bunga

Dalam masalah ini terdapat 3 kelas bunga:

* Iris setosa
* Iris virginica
* Iris versicolor

dan 4 buah fitur:
* Sepal Length
* Sepal Width
* Petal Length
* Petal Width


<table>
  <tr><td>
    <img src="https://www.tensorflow.org/images/iris_three_species.jpg"
         alt="Petal geometry compared for three iris species: Iris setosa, Iris virginica, and Iris versicolor">
  </td></tr>
  <tr><td align="center">
    <b>Figure 1.</b> Iris setosa, Iris versicolor, and Iris virginica </td></tr>
</table>



Impor dahulu semua library yang dibutuhkan

In [ ]:
import pandas as pd #Python Data Analysis Library 
import numpy as np #Python Scientific Library (Umumnya membantu 
#dalam urusan list)

#Selective import modul-modul Scikit Learn 
#(Scikit Learn memiliki banyak modul machine learning)
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error 

Colab dengan bantuan pandas dapat langsung mendownloadkan dataset dari URL yang diberikan.
Pandas akan membantu memisahkan file csv langsung menjadi dataset (numpy array).

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
new_names = ['sepal_length','sepal_width','petal_length','petal_width','iris_class']
dataset = pd.read_csv(url, names=new_names, skiprows=0, delimiter=',')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   iris_class    150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Mari kita amati data yang baru saja di download

In [ ]:
dataset.head(6)
 #change head with sample and tail.

sepal_length  sepal_width  petal_length  petal_width   iris_class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa

In [ ]:
dataset.groupby('iris_class').count()

sepal_length  sepal_width  petal_length  petal_width
iris_class                                                           
Iris-setosa                50           50            50           50
Iris-versicolor            50           50            50           50
Iris-virginica             50           50            50           50

In [ ]:
y = dataset['iris_class']
x = dataset.drop(['iris_class'], axis=1)

print ("dataset : ",dataset.shape)
print ("x : ",x.shape)
print ("y : ",y.shape)


dataset :  (150, 5)
x :  (150, 4)
y :  (150,)


Untuk memudahkan klasifikasi, terutama pada Neural Network maka kita perlu convert ke **one hot** mapping.


Convert:

100: Iris setosa

010: Iris versicolor

001: Iris virginica

In [ ]:
#one hot encoding
y=pd.get_dummies(y)
y.sample(7)

Iris-setosa  Iris-versicolor  Iris-virginica
144            0                0               1
2              1                0               0
76             0                1               0
134            0                0               1
33             1                0               0
123            0                0               1
7              1                0               0

In [ ]:
# Generate Training and Validation Sets
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3) #0.3 data sebagai data test

#converting to float 32bit
x_train = np.array(x_train).astype(np.float32)
x_test  = np.array(x_test).astype(np.float32)
y_train = np.array(y_train).astype(np.float32)
y_test  = np.array(y_test).astype(np.float32)

#print data split for validation
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(105, 4) (105, 3)
(45, 4) (45, 3)


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
print(pca.components_)

[0.92461621 0.05301557 0.01718514 0.00518309]
[25.08986398  6.00785254  3.42053538  1.87850234]
[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]
 [-0.58099728  0.59641809  0.07252408  0.54906091]
 [ 0.31725455 -0.32409435 -0.47971899  0.75112056]]


### Pemanfaatan Machine Learning sederhana k-NN (k-nearest neighbor)

In [ ]:
# K-Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

Model = KNeighborsClassifier(n_neighbors=7) #Inisialisasi model Machine Learning yang digunakan.
Model.fit(x_train, y_train) #Proses training hanya 1 baris ini saja.
y_pred = Model.predict(x_test)

print(classification_report(y_test, y_pred))  # Mencetak Summary 
print(confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))) # Mencetak Conf Matrix
print('accuracy is',accuracy_score(y_pred,y_test)) # Mencetak Accuracy score


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.93      1.00      0.97        14
           2       1.00      0.92      0.96        13

   micro avg       0.98      0.98      0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45
 samples avg       0.98      0.98      0.98        45

[[18  0  0]
 [ 0 14  0]
 [ 0  1 12]]
accuracy is 0.9777777777777777


### MLP  with Scikit Learn

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
Model = MLPClassifier(hidden_layer_sizes=(10,5),  
                      max_iter=200, 
                      alpha=0.01, 
                      solver='sgd', verbose=1,  
                      random_state=121) 
h=Model.fit(x_train,y_train)
y_pred=Model.predict(x_test)

print(classification_report(y_test,y_pred)) # Mencetak Summary 

print(confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1))) # Mencetak Confusion Matrix 

print('accuracy is ',accuracy_score(y_pred,y_test)) #Accuracy Score

Iteration 1, loss = 2.54966093
Iteration 2, loss = 2.50653338
Iteration 3, loss = 2.45055385
Iteration 4, loss = 2.38843251
Iteration 5, loss = 2.32619151
Iteration 6, loss = 2.26565908
Iteration 7, loss = 2.20820737
Iteration 8, loss = 2.15407091
Iteration 9, loss = 2.10461331
Iteration 10, loss = 2.06069710
Iteration 11, loss = 2.02304578
Iteration 12, loss = 1.99146575
Iteration 13, loss = 1.96545261
Iteration 14, loss = 1.94397958
Iteration 15, loss = 1.92700855
Iteration 16, loss = 1.91364217
Iteration 17, loss = 1.90453526
Iteration 18, loss = 1.89874549
Iteration 19, loss = 1.89518598
Iteration 20, loss = 1.89262707
Iteration 21, loss = 1.89040107
Iteration 22, loss = 1.88816102
Iteration 23, loss = 1.88557022
Iteration 24, loss = 1.88250910
Iteration 25, loss = 1.87895551
Iteration 26, loss = 1.87512079
Iteration 27, loss = 1.87099589
Iteration 28, loss = 1.86664270
Iteration 29, loss = 1.86215923
Iteration 30, loss = 1.85770283
Iteration 31, loss = 1.85315326
Iteration 32, los

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import matplotlib.pyplot as plt

plt.plot(h.loss_curve_)
plt.title('Loss History')
plt.xlabel('epoch')
plt.legend(['Loss'])

### Menghubungkan Colab ke Google Drive

Colab dapat dengan mudah dihubungkan ke Google Drive untuk dapat membaca berbagai jenis file di Google Drive.

Berikut adalah script untuk mounting Google Drive sebagai folder di colab.

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Berikut adalah contoh code untuk membaca file gambar di Google Drive kita.

Setelah ter-mount, root Google Drive ada di **""/content/gdrive/My Drive/"**



In [ ]:
import cv2 #Import Open CV
import matplotlib.pyplot as plt #matplotlib bisa digunakan untuk menampilkan gambar  
img = cv2.imread("/content/gdrive/My Drive/puppy-development.jpg")
plt.imshow(img)

Gambar load OpenCV (cv2) warnanya terbalik antara chanel biru dengan merahnya karena itu harus dibalik dengan fungsi **cv2.cvtColor**

In [ ]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)

Colab juga dapat menerima upload file secara langsung yang nantinya akan disimpan pada root folder.

In [ ]:
from google.colab import files
uploaded = files.upload()
img = cv2.imread('Yosi.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)